name: Generate rockspecs

on:
  push:
    branches: master
    paths:
      - types/**

jobs:
  Upload-Types:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@master

    - uses: luarocks/gh-actions-lua@master
      with:
        luaVersion: "5.4"
    - uses: luarocks/gh-actions-luarocks@master

    - name: Install tl + luafilesystem
      run: |
        luarocks install tl
        luarocks install luafilesystem
        luarocks install luafilesystem-tl-type

    - name: Run rockspec generation
      run: |
        tl run ./scripts/generate_rockspecs.tl

    - name: Upload Rockspecs
      env:
        GITHUB_TOKEN: ${{ secrets.TEAL_TYPES_BOT_PAT }}
      run: |
        git config user.name "teal-types-bot"
        git config user.email "teal-types-bot@users.noreply.github.com"

        BRANCH="update/rockspecs-${{ github.run_id }}"

        git checkout -b "$BRANCH"
        git add rockspecs scripts
        git commit -m 'updated rockspecs'
        
        gh pr create -B master -H "$BRANCH" --title 'Generated rockspecs' --body-file ./scripts/updated-rockspecs.txt
